---
title: "GenevAnalytics"
output: html_document
---

library(devtools)
devtools::install_github("JimmyDang14/givedata")
library(dplyr)
library(givedata)

data("DepensesInvestiss_00_17", package="givedata")
ls()
DepensesInvestiss_00_17 %>% head()

data("Loyermoyen100m2_06_19", package="givedata")
ls()
Loyermoyen100m2_06_19 %>% head()

data("NEcolePrimaire", package="givedata")
ls()
NEcolePrimaire %>% head()

data("NHabitants_00_19", package="givedata")
ls()
NHabitants_00_19 %>% head()

data("NInfractions_08_19", package="givedata")
ls()
NInfractions_08_19 %>% head()

data("NMedecins", package="givedata")
ls()
NMedecins %>% head()

data("NParcs", package="givedata")
ls()
NParcs %>% head()

data("NSupermarches", package="givedata")
ls()
NSupermarches %>% head()

data("PMedianeAppart100m2_00_17", package="givedata")
ls()
PMedianeAppart100m2_00_17 %>% head()

data("PMedianeVilla_00_17", package="givedata")
ls()
PMedianeVilla_00_17 %>% head()

data("Superficie", package="givedata")
ls()
Superficie %>% head()


